org.gradle.configuration-cache=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.jvmargs=-Xmx4G

group_id=io.github.jmecn
mod_id=ftb_quest_export
mod_name=FTB Quest Export
mod_version=0.2.10
mod_authors=jmecn
mod_description=Exports FTB Quests quest books to quest-export bundles for QuestBook-Modern.
mod_license=MIT
archives_name=ftb-quest-export

minecraft_version=1.20.1
forge_version=47.4.13
mdg_legacy_version=2.0.119

ftb_quests_version=2001.4.22
ftb_library_version=2001.2.12
ftb_teams_version=2001.3.2
ftb_filter_system_version=20.0.1
architectury_version=9.2.14
